const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const iconSizes = [16, 32, 48, 64, 128, 256, 512, 1024];
const svgPath = path.join(__dirname, '../build/icons/icon.svg');
const iconsDir = path.join(__dirname, '../build/icons');

// Ensure icons directory exists
if (!fs.existsSync(iconsDir)) {
  fs.mkdirSync(iconsDir, { recursive: true });
}

async function generateIcons() {
  console.log('Generating icons from SVG...');
  
  try {
    const svgBuffer = fs.readFileSync(svgPath);
    
    // Generate PNG icons for each size
    for (const size of iconSizes) {
      const outputPath = path.join(iconsDir, `icon-${size}x${size}.png`);
      await sharp(svgBuffer)
        .resize(size, size)
        .png()
        .toFile(outputPath);
      console.log(`✓ Generated ${size}x${size} icon`);
    }
    
    // Generate macOS .icns (requires iconutil, but we'll create the iconset structure)
    console.log('\nGenerating macOS icon set...');
    const macIconsetPath = path.join(iconsDir, 'icon.iconset');
    if (!fs.existsSync(macIconsetPath)) {
      fs.mkdirSync(macIconsetPath, { recursive: true });
    }
    
    // macOS requires specific sizes
    const macSizes = [
      { size: 16, name: 'icon_16x16.png' },
      { size: 32, name: 'icon_16x16@2x.png' },
      { size: 32, name: 'icon_32x32.png' },
      { size: 64, name: 'icon_32x32@2x.png' },
      { size: 128, name: 'icon_128x128.png' },
      { size: 256, name: 'icon_128x128@2x.png' },
      { size: 256, name: 'icon_256x256.png' },
      { size: 512, name: 'icon_256x256@2x.png' },
      { size: 512, name: 'icon_512x512.png' },
      { size: 1024, name: 'icon_512x512@2x.png' },
    ];
    
    for (const { size, name } of macSizes) {
      const outputPath = path.join(macIconsetPath, name);
      await sharp(svgBuffer)
        .resize(size, size)
        .png()
        .toFile(outputPath);
    }
    console.log('✓ Generated macOS iconset (use: iconutil -c icns icon.iconset)');
    
    // Generate Windows .ico (we'll create a multi-size ICO)
    console.log('\nGenerating Windows icon...');
    const icoSizes = [16, 32, 48, 64, 128, 256];
    // Note: electron-builder will handle ICO generation, but we create the PNGs
    console.log('✓ Windows ICO will be generated by electron-builder');
    
    console.log('\n✓ All icons generated successfully!');
  } catch (error) {
    console.error('Error generating icons:', error);
    process.exit(1);
  }
}

generateIcons();

