const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const svgPath = path.join(__dirname, '../../../branding/logo.svg');

const targets = [
  {
    name: 'Desktop',
    dir: path.join(__dirname, '../build/icons'),
    sizes: [16, 32, 48, 64, 128, 256, 512, 1024],
    namePattern: (size) => `icon-${size}x${size}.png`,
  },
  {
    name: 'Extension',
    dir: path.join(__dirname, '../../extension/public/icons'),
    sizes: [16, 48, 128],
    namePattern: (size) => `icon-${size}.png`,
  },
];

async function generateIcons() {
  console.log('Generating icons from SVG...\n');

  try {
    const svgBuffer = fs.readFileSync(svgPath);

    for (const target of targets) {
      console.log(`--- ${target.name} ---`);
      if (!fs.existsSync(target.dir)) {
        fs.mkdirSync(target.dir, { recursive: true });
      }

      for (const size of target.sizes) {
        const outputPath = path.join(target.dir, target.namePattern(size));
        await sharp(svgBuffer)
          .resize(size, size)
          .png()
          .toFile(outputPath);
        console.log(`  ✓ ${target.namePattern(size)}`);
      }
    }

    // Generate macOS .icns iconset structure
    console.log('\n--- macOS iconset ---');
    const macIconsetPath = path.join(targets[0].dir, 'icon.iconset');
    if (!fs.existsSync(macIconsetPath)) {
      fs.mkdirSync(macIconsetPath, { recursive: true });
    }

    const macSizes = [
      { size: 16, name: 'icon_16x16.png' },
      { size: 32, name: 'icon_16x16@2x.png' },
      { size: 32, name: 'icon_32x32.png' },
      { size: 64, name: 'icon_32x32@2x.png' },
      { size: 128, name: 'icon_128x128.png' },
      { size: 256, name: 'icon_128x128@2x.png' },
      { size: 256, name: 'icon_256x256.png' },
      { size: 512, name: 'icon_256x256@2x.png' },
      { size: 512, name: 'icon_512x512.png' },
      { size: 1024, name: 'icon_512x512@2x.png' },
    ];

    for (const { size, name } of macSizes) {
      const outputPath = path.join(macIconsetPath, name);
      await sharp(svgBuffer)
        .resize(size, size)
        .png()
        .toFile(outputPath);
    }
    console.log('  ✓ Generated macOS iconset (use: iconutil -c icns icon.iconset)');
    console.log('  ✓ Windows ICO will be generated by electron-builder');

    // Copy SVG to desktop icons dir
    fs.copyFileSync(svgPath, path.join(targets[0].dir, 'icon.svg'));
    console.log('\n✓ All icons generated successfully!');
  } catch (error) {
    console.error('Error generating icons:', error);
    process.exit(1);
  }
}

generateIcons();

